### ISSUE TITLE
Consider contributing back?

### ISSUE THREAD

**Issue by nicolas-grekas** [php-ffi/var-dumper#1]
Hi, I just discovered about this project and I'm wondering if you'd consider contributing your casters to var-dumper directly?
We already have a caster for FFI: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/VarDumper/Caster/FFICaster.php

I don't know FFI well enough to be useful on the topic but maybe there's something from your experience that can be improved there?
Or is this project too opinionated?

**Comment by SerafimArts** [comment]
@nicolas-grekas Hey! I'm waiting for an answer to this question in order to add this changes: https://github.com/symfony/symfony/issues/47668#issuecomment-1256989834 =)

**Comment by nicolas-grekas** [comment]
Arf sorry I forgot about this :grimacing:
